name: kibot

on:
  workflow_dispatch:
  push:
    paths:
    - 'Kicad_Project/*.kicad_sch'
    - 'Kicad_Project/*.kicad_pcb'
    - '*.kibot.yaml'
    - '.github/workflows/main.yml'
  pull_request:
    paths:
    - 'Kicad_Project/*.kicad_sch'
    - 'Kicad_Project/*.kicad_pcb'
    - '*.kibot.yaml'
    - '.github/workflows/main.yml'

jobs:
  kibot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_k7
      with:
        config: config.kibot.yaml
        dir: output
        schema: 'Kicad_Project/CCC_ESC.kicad_sch'
        board: 'Kicad_Project/CCC_ESC.kicad_pcb'
    - name: list results
      run: 'ls -R -l'
    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: MP2_ESC_JLCPCB
        path: './output/JLCPCB/CCC_ESC-JLCPCB.zip'
